export const players = [
  {
    id: 1,
    name: 'moses',
    surname: 'brown',
    position: 'c',
    height: `7'2"`,
    weight: 245,
    fg: 100,
    pts: 1.0,
    assist: 0.0,
    gameNumber: 9,
    img: 'https://www.mavs.com/wp-content/uploads/2021/07/Moses_Brown_profile.png',
    about: `Brown (7-2, 245) holds career averages of 7.3 points (.540 FG%), 7.6 rebounds, 0.9 blocks and 18.3 minutes in 52 games (32 starts) with Portland and Oklahoma City. The 21-year-old averaged 8.6 points, 8.9 rebounds, 0.7 steals, 1.1 blocks and 21.4 minutes in 43 games (32 starts) with the Thunder last season. He recorded 21 […]`
  },
  {
    id: 2,
    name: 'sterling',
    surname: 'brown',
    position: 'p-g',
    height: `6'5"`,
    weight: 219,
    fg: 23.5,
    fg3: 20,
    pts: 2.3,
    assist: 0.7,
    gameNumber: 0,
    img: 'https://www.mavs.com/wp-content/uploads/2021/08/brown_profile.png',
    about: `Appeared in 112 career games (11 starts) over his first 2 seasons in the NBA and holds career averages of 5.3 points, 2.9 rebounds and 1.0 assist … played in 14 playoff games SMU’s all-time leader in wins (109) and games played (136), and ranks second for career 3-point field goal percentage (.451) 2017 Reese’s […]`
  },
  {
    id: 3,
    name: 'jajlen',
    surname: 'brunson',
    position: 'g',
    height: `6'1"`,
    weight: 190,
    fg: 49.5,
    fg3: 35,
    pts: 14.9,
    assist: 4.6,
    gameNumber: 13,
    img: 'https://www.mavs.com/wp-content/uploads/2019/07/Brunson-Profile.png',
    about: `Jalen Marquis Brunson was born in New Brunswick, New Jersey, to Rick and Sandra Brunson. His parents were both volleyball players at Temple University, and Rick went on to play nine seasons in the NBA. Jalen has a younger sister, Erica. He attended Stevenson High School in Lincolnshire, Illinois, where he was a two-time Illinois […]`
  },
  {
    id: 4,
    name: 'reggie',
    surname: 'bullok',
    position: 'g-f',
    height: `6'6"`,
    weight: 205,
    fg: 38.5,
    fg3: 32.1,
    pts: 6.8,
    assist: 0.6,
    gameNumber: 25,
    img: 'https://www.mavs.com/wp-content/uploads/2021/08/R_Bullock_Profile.png',
    about: `Reggie Bullock played college basketball for the University of North Carolina (2010–2013), where he finished his career ranked eighth in school history with 188 three-pointers before being selected by the Los Angeles Clippers with the 25th overall pick in the 2013 NBA Draft. Bullock finished second in the NBA in three-point percentage during the 2017-18 […]`
  },
  {
    id: 5,
    name: 'trey',
    surname: 'burke',
    position: 'g',
    height: `6'0"`,
    weight: 185,
    fg: 41.7,
    fg3: 40,
    pts: 4,
    assist: 1.0,
    gameNumber: 3,
    img: 'https://www.mavs.com/wp-content/uploads/2021/10/Trey_Burke-Profile.png',
    about: `Alfonso Clark “Trey” Burke III was born on November 12, 1992 in Columbus, Ohio. He is the son of Ronda and Alfonso Clark “Benji” Burke II. Burke’s father played collegiately at Division II Northwest Missouri State University. Burke played high school basketball at Northland High, where he was a teammate of future Ohio State star, […]`
  },
  {
    id: 6,
    name: 'willie ',
    surname: 'bcauley-stein',
    position: 'c',
    height: `7'0"`,
    weight: 240,
    fg: 42.1,
    pts: 1.3,
    assist: 0.5,
    gameNumber: 33,
    img: 'https://www.mavs.com/wp-content/uploads/2020/01/WCS_Profile_Right.png',
    about: `Willie Trill Cauley-Stein was born in Spearville, Kansas, to Willie Cauley and Marlene Stein. His father played college basketball at Dodge City Community College and for one season at the University of Pittsburgh. As a sophomore, Cauley-Stein transferred to Olathe Northwest High School in Olathe, Kansas. During his junior season, he averaged 15.8 points and […]`
  },
  {
    id: 7,
    name: 'luka',
    surname: 'dončić',
    position: 'f-g',
    height: `6'7"`,
    weight: 230,
    fg: 43.8,
    fg3: 30.9,
    pts: 25.1,
    assist: 7.7,
    gameNumber: 77,
    img: 'https://www.mavs.com/wp-content/uploads/2019/07/Luka_Doncic_Profile.png',
    about: `Luka Dončić was born in Ljubljana, Slovenia, to Mirjam Poterbin and Sasha Dončić. His father played pro basketball in Slovenia while his godfather, Radoslav Nesterovic, played 12 seasons in the NBA and won a title with the San Antonio Spurs in 2005. Luka began playing basketball at age eight with the youth teams of Olimpija. […]`
  },
  {
    id: 8,
    name: 'dorian',
    surname: 'finney-smith',
    position: 'f',
    height: `6'7"`,
    weight: 220,
    fg: 36.7,
    fg3: 28.8,
    pts: 8.2,
    assist: 1.3,
    gameNumber: 10,
    img: `https://www.mavs.com/wp-content/uploads/2021/08/DFS_Profile.png`,
    about: `Dorian Lawrence Finney-Smith was born in Portsmouth, Virginia, to Desiree Finney-Jones. His brother, Ben Finney, played basketball at Old Dominion. Finney-Smith attended and played basketball for I.C. Norcom High School in Portsmouth. As a junior, he averaged 19.7 points, 13 rebounds, six assists, three steals and two blocks per game. The following season, he posted […]`
  },
  {
    id: 9,
    name: 'josh',
    surname: 'green',
    position: 'g',
    height: `6'5"`,
    weight: 200,
    fg: 33.3,
    pts: 0.9,
    assist: 0.3,
    gameNumber: 8,
    img: 'https://www.mavs.com/wp-content/uploads/2020/12/J_green_Profile.png',
    about: `Josh Green was born Nov. 16, 2000 in Sydney, New South Wales. He was born to Australian mother Cahla and American-born father Delmas. Green began playing basketball at five years old, in suburban Syndey, when his mother began coaching him. Green also played Australian rules football, track athletics, rugby, soccer and swimming. By the time […]`
  },
  {
    id: 10,
    name: 'tim',
    surname: 'hardaway jr',
    position: 'g-f',
    height: `6'5"`,
    weight: 205,
    fg: 40.4,
    fg3: 37.1,
    pts: 14.2,
    assist: 2.3,
    gameNumber: 11,
    img: 'https://www.mavs.com/wp-content/uploads/2019/02/THJ_Profile.png',
    about: `Timothy Duane Hardaway Jr. was born in Alameda, California, to Yolanda Hardaway and Tim Hardaway Sr. His father was a five-time All-Star in the NBA. Tim Hardaway Jr. attended Palmer Trinity School as a high-school freshman, playing football before focusing on basketball. He transferred to Miami Palmetto High School prior to his sophomore season, and […]`
  },
  {
    id: 11,
    name: 'maxi',
    surname: 'kleber',
    position: 'f',
    height: `6'10"`,
    weight: 240,
    fg: 50,
    fg3: 47.8,
    pts: 7.2,
    assist: 0.5,
    gameNumber: 42,
    img: 'https://www.mavs.com/wp-content/uploads/2019/07/Maxi_Profile.png',
    about: `Maximilian “Maxi” Kleber was born in Wurzburg, Germany in 1992. He is from the same hometown as former Mavericks great (and former teammate) Dirk Nowitzki. Kleber played youth basketball with TG Veitshochheim, SC Heuchelhof and TG Wurzburg before turning pro during the 2011-12 season. Kleber was the Mavericks’ nominee for the February 2020 NBA Cares […]`
  },
  {
    id: 12,
    name: 'boban',
    surname: 'marjanović',
    position: 'c',
    height: `7'3"`,
    weight: 290,
    fg: 68.2,
    pts: 5.5,
    assist: 0.3,
    gameNumber: 51,
    img: 'https://www.mavs.com/wp-content/uploads/2019/07/Boban_Profile.png',
    about: `Boban Marjanović was born in Boljevac, Serbia, Yugoslavia in 1988. He began playing youth basketball with the Boljevac-based club Rtanj. When he was 14, Marjanović moved to Serbian professional team Hemofarm, playing on their youth squads until the 2005-06 season. “Bobi” has an interest in acting. In 2015, he made a cameo in the Serbian […]`
  },
  {
    id: 13,
    name: 'kristaps',
    surname: 'porzingins',
    position: 'f-c',
    height: `7'3"`,
    weight: 240,
    fg: 42.1,
    fg3: 30,
    pts: 17.9,
    assist: 1.1,
    gameNumber: 6,
    img: 'https://www.mavs.com/wp-content/uploads/2019/07/KP_Profile.png',
    about: `Kristaps Porzingis was born in Liepaja, Latvia, to Talis and Ingrida Porzingis. He comes from a family of basketball players. His father played semi-professional hoops and his mother played on Latvia’s youth national teams. Porzingis’ oldest brother, Janis, played for 14 years in multiple European national domestic leagues, and another older brother, Martins, played basketball […]`
  },
];
